[features]
seeds = false
skip-lint = false
[programs.localnet]
my_app = "5zMhWKsdPYNhocSf1Jhvr5AgtLw7seZwk6Q7ycQRVfsP"
[programs.devnet]
my_app = "5zMhWKsdPYNhocSf1Jhvr5AgtLw7seZwk6Q7ycQRVfsP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
